---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Make sshd configuration file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Restart ssh
