---
- name: Download samurai kernel
  get_url:
    url: "https://github.com/0xAFz/samurai/releases/download/v{{ samurai_version }}/samurai-{{ samurai_kernel_version }}-amd64.deb"
    dest: "/tmp/samurai.deb"

- name: Install samurai kernel
  apt:
    deb: /tmp/samurai.deb
