## basic package list for installation
packages:
- vim
- bash-completion
- curl
- ca-certificates
- unzip
- net-tools
- dnsutils
- tcpdump
- ethtool

## sshd configuration
sshd_config:
  Port: "{{ ansible_port }}"
  ListenAddress: 0.0.0.0
  PermitRootLogin: without-password
  PasswordAuthentication: "no"
  AllowUsers: root
  AllowGroups: root

## firewall system
## supported: nftables, iptables, none
firewall: none

## firewall configuration
firewall_config:
  network_adapter_access:
    - lo
  tcp_port_access:
    - 8084
    - 8082
  udp_port_access:
    - 8084
    - 8082
  trusted_range:
    - 10.44.44.0/24
    - "{{ hostvars['external-network'].ansible_host }}/32"
    - "{{ hostvars['internal-network'].ansible_host }}/32"

## packet DSCP configuration
## https://en.wikipedia.org/wiki/Differentiated_services
dscp: true

## session timeout setting (seconds)
timeout_time: 600

## resolv.conf name servers
dns_v4: 1.1.1.1
dns_v4_fallback: 1.0.0.1
dns_v6: 2606:4700:4700::1111
dns_v6_fallback: 2606:4700:4700::1001

## DNS variables for systemd-resolved
dns: 1.1.1.1
fallback_dns: 1.0.0.1
dnssec: allow-downgrade
dns_over_tls: opportunistic

## limit.conf variables
limit_nofile_hard: 1000000
limit_nofile_soft: 1000000
limit_nproc_hard: 10000
limit_nproc_soft: 10000

## qdisc configuration
fq_codel_target: 500us
fq_codel_interval: 10ms
fq_codel_limit: 1024
fq_codel_flows: 1024
fq_codel_quantum: 256

## NIC configuration
##
## https://www.kernel.org/doc/Documentation/networking/segmentation-offloads.txt
## https://en.wikipedia.org/wiki/TCP_offload_engine
##
tso: false   # TCP Segmentation Offload
gso: false   # Generic Segmentation Offload
gro: false   # Generic Receive Offload

## RX/TX queue polling interval
rx_usecs: 0
tx_usecs: 0

## sysctl configuration variables
sysctl_config:
  net.core.busy_read: 100
  net.core.busy_poll: 100
  net.core.somaxconn: 512
  net.ipv4.tcp_fin_timeout: 10
  net.ipv4.tcp_keepalive_time: 120
  net.ipv4.tcp_ecn: 0
  net.ipv4.tcp_sack: 0
  net.ipv4.tcp_mtu_probing: 0
  net.ipv4.tcp_timestamps: 0
  net.ipv4.tcp_keepalive_intvl: 20
  net.ipv4.tcp_keepalive_probes: 3
  net.ipv4.tcp_max_orphans: 2048
  net.ipv4.tcp_retries2: 3
  net.ipv4.tcp_synack_retries: 2
  net.ipv4.tcp_window_scaling: 1
  net.ipv4.tcp_slow_start_after_idle: 1
  net.ipv4.tcp_max_tw_buckets: 2048
  net.ipv4.tcp_syncookies: 1
  net.ipv4.tcp_tw_reuse: 1
  net.ipv4.tcp_max_syn_backlog: 128
  net.ipv4.tcp_rmem: "4096 87380 262144"
  net.ipv4.tcp_wmem: "4096 16384 262144"
  net.ipv4.tcp_low_latency: 1
  net.ipv4.tcp_fastopen: 3
  net.core.rmem_default: 65536
  net.core.wmem_default: 65536
  net.core.rmem_max: 262144
  net.core.wmem_max: 262144
  net.core.optmem_max: 32768
  net.core.netdev_max_backlog: 1024
  net.unix.max_dgram_qlen: 512
  net.ipv4.udp_rmem_min: 16384
  net.ipv4.udp_wmem_min: 16384
  net.ipv4.udp_l3mdev_accept: 1
  net.ipv4.ip_default_ttl: 64
  net.core.default_qdisc: fq_codel
  net.ipv4.tcp_congestion_control: cubic
  net.ipv4.icmp_echo_ignore_all: 0
  net.ipv4.ip_forward: 1
  net.ipv4.conf.all.forwarding: 1
  net.ipv6.conf.all.forwarding: 1
  vm.max_map_count: 262144
  vm.swappiness: 0
  vm.compaction_proactiveness: 0
  vm.dirty_ratio: 5
  vm.dirty_background_ratio: 5
  fs.file-max: 1500000
  net.ipv4.conf.default.rp_filter: 0
  net.ipv4.conf.all.rp_filter: 0
  net.bridge.bridge-nf-call-iptables: 0
  net.bridge.bridge-nf-call-ip6tables: 0
  kernel.printk: "3 4 1 3"
  net.netfilter.nf_conntrack_max: "{{ '0' if firewall == 'none' else '262144' }}"
  net.netfilter.nf_conntrack_tcp_timeout_established: "{{ '0' if firewall == 'none' else '900' }}"
  net.netfilter.nf_conntrack_tcp_timeout_close_wait: "{{ '0' if firewall == 'none' else '10' }}"
  net.netfilter.nf_conntrack_tcp_timeout_syn_recv: "{{ '0' if firewall == 'none' else '30' }}"
