## basic package list for installation
packages:
- vim
- bash-completion
- curl
- ca-certificates
- unzip
- net-tools
- dnsutils
- tcpdump
- ethtool
- openssl

## samurai kernel (amd64)
## not stable for all platforms!
samurai: false
samurai_version: 0.2.3
samurai_kernel_version: 6.1.131

## monitoring (prometheus)
monitoring: false
node_exporter_listen_address: ":9100"

## sshd configuration
sshd_config:
  Port: "{{ ansible_port }}"
  ListenAddress: 0.0.0.0
  PermitRootLogin: without-password
  PasswordAuthentication: "no"
  AllowUsers: root
  AllowGroups: root

## name servers
dns: 1.1.1.1
dns_fallback: 1.0.0.1
dns_v6: 2606:4700:4700::1111
dns_v6_fallback: 2606:4700:4700::1001

## limits
limit_nofile_hard: 1000000
limit_nofile_soft: 1000000
limit_nproc_hard: 10000
limit_nproc_soft: 10000
